Frame demuxer

diff --git a/bin/scenes_init b/bin/scenes_init
--- a/bin/scenes_init
+++ b/bin/scenes_init
@@ -1,8 +1,10 @@
 #! /usr/bin/env bash
 
+test -d "$1" || { printf '%s: invalid directory -- %s\n' $(basename "$0") "$1" && exit 4; }
+
 scene_init() {
     jq ". += {\"name\":\"${1#**/}\", \"events\":[], \"vsrc\":\"${1#**/}.mp4\"}" <<< '{}' > "$1/scene.json"
-    echo -e "EXT_IN = .png\nFPS = 10" > "$1/config.mk"
+    echo -e "EXT_IN = png\nFPS = 6" > "$1/config.mk"
 }
 
 export -f scene_init
